### ISSUE TITLE
Applicant Decision

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#12]
Reviewers will also need the ability to apply a decision to an applicant. This will most likely involve assigning the applicant an application state (pending, accepted, waitlisted, rejected), recording the reviewer, and assigning the applicant to a notification wave. 

We will need to discuss exactly how much reviewer information we want to store. For example, should we only store who modified the decision last, or should we have who changed which portion of the decision?

This resource should only be available to properly-roled users. It will likely work in parallel with the socket microservice to keep clients alert about changes made to an applicant (without either system needing to know about the other directly).

**Comment by nmagerko** [comment]
Applicant decisions have changed significantly since this issue was opened. I will revisit the description soon once I've coordinated with the admissions team.

**Comment by tommypacker** [comment]
So according to experience we're going to be doing a two-round decision process where one reviewer applies a decision, and then Yasha goes in and finalizes/confirms the decision

**Comment by nmagerko** [comment]
Finished by #54
