### ISSUE TITLE
Applicant Decision Utilities

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#13]
In addition to the ability to view and applicant and make a decision, reviewers will also appreciate some help in getting the process done. It is expected that a portion of the review process will not be random, so certain API utilities will be necessary to be sure that we can help the reviewers out.

There has been some discussion already about the potential of providing resume summaries in addition to metrics related to how applicants compare to one another based on a variety of criteria. I would like to have that discussion here along with ideas for how we would implement these utilities and/or what existing libraries we could use to do so.

**Comment by nmagerko** [comment]
I think this issue will also include any random-fill functionality we decide to implement as well. For instance, it might be useful to have certain utilities to provide ranking functionality and then provide a utility to randomly select some number of applicants for acceptance.

**Comment by nmagerko** [comment]
And, of course, we'll need this to include some variety of statistics for reviewers (also part of this).

**Comment by tommypacker** [comment]
Just talked to Experience, all we need is to provide a large table of every applicant

**Comment by nmagerko** [comment]
A paginated table with sorting is probably what we should aim for instead of a query of everyone. Not a fan of gigantic queries.

**Comment by nmagerko** [comment]
Finished by #54
