### ISSUE TITLE
Applicant RSVP

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#14]
Accepted applicants will need to tell us whether or not they are coming to the event. In doing so, they will allow us to find out whether or not we need to admit more waitlisted applicants, expand our resources for the event, and so on.

The feature itself will be rather basic, providing the ability to select whether or not the applicant will be attending, how the applicants will be arriving (transportation), and updating any related statistics. Attendees should also be added to the appropriate mailing list(s).

**Comment by nmagerko** [comment]
This may be put on hold or eliminated depending on how we handle admissions. This year might see RSVP somewhat rolled into admissions decisions in a way that was not quite like last year's process.

**Comment by YashoSharma** [comment]
Resolved by #53
