### ISSUE TITLE
Hacker Help Chat

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#16]
As part of how we handle help requests, we will probably want to allow those individuals requesting help to interact with mentors/organizational staff without necessarily having to go find someone in-person.

How exactly we want to implement this is up for discussion, although we have discussed just creating chat functionality via SocketIO. I am a bit wary about following through with this implementation, since creating a completely functional chat application seems a bit extreme. Perhaps we could make use of existing infrastructure instead (a mentor Slack, a Slack integration, pre-defined messages, etc).

**Comment by tommypacker** [comment]
I prefer an option with Slack because there's no point in reimplementing a full-blown chat app

**Comment by nmagerko** [comment]
Closing because this won't be a part of the API (unless we change our minds).

**Comment by incfidelibus** [comment]
Could your husband/wife possibly be cheating on you or hiding something from you? Do you want to hack any email account, mobile phone, facebook, website? Or perhaps, you need to boost your credit score, delete criminal records, change your grades? Find out all the truth you need to know with the help of a certified ethical hacker, contact: reputablehacker@gmail.com
