### ISSUE TITLE
Finding user by ID fails due to middleware permissions

### ISSUE THREAD

**Issue by prevosis** [HackIllinois/api-2017#18]
In the wiki, the endpoint `GET /v1/user/{:id}` is allowed for `ADMIN` or `STAFF` roles, however, the current middleware permissions module only lets this endpoint be accessed by the user with the requested ID (i.e. if user with ID 2 goes to `/v1/user/2`). Is this the desired behavior or should it be in line with what is in the wiki?

Relevant files: 
- [middleware.permissions](https://github.com/HackIllinois/api-2017/blob/staging/api/v1/middleware/permission.js)

- [controllers.userController](https://github.com/HackIllinois/api-2017/blob/staging/api/v1/controllers/userController.js)

**Comment by prevosis** [comment]
Wanted to mention as well that there is an easy fix here -- in [middleware.permissions](
https://github.com/HackIllinois/api-2017/blob/staging/api/v1/middleware/permission.js) line 15, we can add `&& !_.includes(allowed, req.auth,role)` to fix the issue and also follow the guidelines of only having staff / admin roles access the user data.

**Comment by nmagerko** [comment]
Nice catch. You're correct about the current behavior being faulty (we need tests, I know) and the fix. Let's continue the conversation in #19.

**Comment by prevosis** [comment]
Sounds good.

**Comment by prevosis** [comment]
I think we can close this issue as well.
