### ISSUE TITLE
Unit & Integration Testing

### ISSUE THREAD

**Issue by prevosis** [HackIllinois/api-2017#23]
It might be a good idea to add this now before the API gets bigger. I have begun doing this in a separate branch (will prob keep it as a feature branch). My current thoughts are to use [Chai](http://chaijs.com/) and [Mocha](https://mochajs.org/) due to their easy HTTP request libraries, although I'm sure things like Jasmine would work fine as well. My current format is shown below:

```
├── test.js
├── auth
└── user
    ├── accredited.js
    └── index.js
```

Where `test.js` is the main test spec which pulls in tests from `auth` and `user` (which respectively test auth and user functionality, and `accredited` tests user functionality for accredited users). This is just the workflow I have set up right now and there is much room for change.

**Comment by nmagerko** [comment]
Yeah I definitely agree that this needs to start coming together, or we're going to be back-testing everything at the end. If you're willing to work on this or at least get it started, that'd be a big help to us. 

The only thing I'm thinking is that it might be best to split this by API version. So the format you have would just be under a `v1` module. Other than that, it looks good to me.

**Comment by nmagerko** [comment]
There might be some refactoring that we need to do in order to mock the `MailService` and `StorageService` as they are right now, but that won't affect the tests you've listed so far. 

With respect to that, though, I have been thinking about creating separate interfaces and implementations for those services -- currently, they just change their `module.exports` to match whatever the state of the application is (not great).

**Comment by prevosis** [comment]
Yes, it is currently under the `v1` module. But awesome, I can get started on this. I can push up a feature branch for review which will have some basic tests so others can take a look and add their own.

**Comment by prevosis** [comment]
One thing we might have to do is create a feature branch in the source repo so that we can merge commits into there. Then I can make a PR to merge what I have into there.

**Comment by shotaroikeda** [comment]
I've since changed the organization to specific endpoints
```
v1
├── test
│   ├── auth
│   │   ├── hacker.js
│   │   ├── index.js
│   │   └── staff.js
│   ├── test.js
│   ├── testConsts.js
│   ├── testHelper.js
│   └── user
│       ├── admin.js
│       ├── hacker.js
│       ├── index.js
│       └── staff.js
```

There were also some issues with actually running the tests (I think the more recent merges have messed with the old system) so make sure you pull the more recent version.

**Comment by nmagerko** [comment]
We haven't gotten around to integration testing, but we have added our tests. I'm marking this as done.
