### ISSUE TITLE
Rename Promise Imports to Avoid ES6 Naming Conflict

### ISSUE THREAD

**Issue by shotaroikeda** [HackIllinois/api-2017#24]
See: https://github.com/HackIllinois/api-2017/pull/21#discussion-diff-76505904R3

ES6 Supplies their own `Promise` which has a naming conflict with the current imports (`var Promise = require...`). We should change this as a good practice.

**Comment by nmagerko** [comment]
👍

**Comment by nmagerko** [comment]
Finished by #27
