### ISSUE TITLE
Github backed user accounts over custom auth

### ISSUE THREAD

**Issue by narendasan** [HackIllinois/api-2017#29]
From a user experience standpoint the fact that we make all hackers create an account specifically for HackIllinois for 3 key interactions that are spread roughly 2 months apart from each other is kind of hard to justify. It will be a smoother interaction over the course of their time with us if they use their githubs to sign in. 
1. it will be an account that people will remember
2. if the user does not have a github but wants to come to a hackathon let alone an open source hackathon they probably should have one. 
3. login becomes 1 click (max 2 for first time) 

**If we implement this remember to add a way to change the default email, some people don't use the email associated with their github**

**Comment by nmagerko** [comment]
I'd definitely like to integrate this. As we've discussed, it makes a lot of sense, but we have to find time to get it integrated into the existing auth system (not that it's too difficult).

I'll look into finding a contributor (internal or external) that can get started.

**Comment by narendasan** [comment]
Maybe the hackgt guy kuz has been talking about

**Comment by nmagerko** [comment]
Now that we've got a good baseline going, I think we should start on this. We can either handle the OAuth stuff ourselves or shift over to something like `passport.js` which will handle it all for us.

**Comment by narendasan** [comment]
The software engineering in me says do it ourselves, but the code monkey in me says use passport. I think its mostly dependent on the size of the feature backlog, if you have the time would recommend developing a system that integrates well with what is there already. however perhaps passport will let us use other OAuth providers easier, which might be a good thing for the community.

**Comment by tommypacker** [comment]
I think `passport.js` is a better move because we wouldn't need to reinvent the wheel

**Comment by redsn0w422** [comment]
+1 passport

**Comment by YashoSharma** [comment]
Implemented by #128
