### ISSUE TITLE
Caching Layer

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#30]
Right now, almost all of our API routes touch the database. As we continue building, I'd like to add a caching layer to cut down on the number of queries we need to make on frequently-accessed data. This will also give us the chance to add rate-limiting to the API as well.

The implementation I see is as follows:
- Create a `CacheService` to handle all caching operations  
  - We should be able to at least create, fetch, update, and expire keys
  - We should support a local Redis cache for developers (i.e. those without an [active AWS SDK](https://github.com/HackIllinois/api-2017/blob/staging/api/v1/services/StorageService.js#L12)), and use ElastiCache when available (i.e. in production)
- Add caching operations to existing API components
  - Assuming this is finished after registration, it would be nice to at least cache the responses of registration information
  - Feel free to use your judgement with this point

Overall, this should be a pretty straightforward feature, but it will come in handy very quickly.

**Comment by michaelcolomb** [comment]
I'm interested. I have to familiarize myself with the api better and Redis, but I think I can start adding soon.

**Comment by nmagerko** [comment]
Great. Feel free to fork the repo and start working on it as soon as you're ready. 

There will be a contribution file up soon to explain exactly how contributions from external contributors will work, but for now just make sure that you're working in a branch called something like `feature/caching` that is branched off of `staging` (not `master`).

**Comment by nmagerko** [comment]
Removing the `feature` label because this isn't really a feature.

l I think we might have @tommypacker take care of this one. This is probably going to be in the initial release, so it might be best if we have a member who is more familiar with the API take it on. However, as we discussed @michaelcolomb, you should have a look at integration and testing.

**Comment by nmagerko** [comment]
As discussed, we're going to scrap abstracting the cache into a service and instead just have a helper module to just properly initialize the cache module that we're working with (i.e. `redis`).

**Comment by nmagerko** [comment]
Finished with #42
