### ISSUE TITLE
Interest Email Collection

### ISSUE THREAD

**Issue by shotaroikeda** [HackIllinois/api-2017#31]
Before the Hackathon's application opens, we need a system to collect emails so we can notify potential attendees when the event status changes (such as when applications open). 

This would be a plain list of emails, and to query these emails you would need either the `ADMIN`'s or the `STAFF`'s permission.

We could also build this on top of the current User model, by creating default user passwords for everyone. However this would cause confusion when the user comes back to submit an application, as it would seem as if the user already created an account with the backend.

My recommendation would be creating a new `interest` model, where we curate the emails of people who are interested.

**Comment by nmagerko** [comment]
Considering the urgency expressed by the core team in terms of when they wanted this functionality live, I don't think implementing this here would be a good idea. We have yet to release and our target for doing so is still a month away. 

Instead, let's consider making this a core feature later and opt for a more temporary solution now. I think something like Firebase would be reasonable, as the front-end could start using it immediately.

**Comment by nmagerko** [comment]
Closing until we find a reason to revisit this.
