### ISSUE TITLE
Project Listings

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#38]
The admissions team will need to be able to add projects and attach mentors in order to make attendee registration work the way we want it to work. This issue will deal with how that is handled.

The implementation should proceed as follows:
- Create a `Project` model
  - `id` (INT, Required)
  - `name` (VARCHAR 100, Required)
  - `description` (VARCHAR 200, Required)
  - `repo` (VARCHAR 255, Required)
  - `is_published` (TINYINT 1, Default=0)
- Crete endpoints to allow for project creation/retrieval/update
  - POSTs should create a project (STAFF+)
  - GETs should retrieve the project (any authenticated user)
  - PUTs should update the project (STAFF+)
- Create a `ProjectMentor` model
  - `id` (INT, Required)
  - `project_id` (INT, FK Project.id, Required)
  - `mentor_id` (INT, FK Mentor.id, Required)
- Create endpoints to allow for mentor assignment/removal
  - POSTs should query for the project-mentor combination to make see if it already exists (like `MailingList` and `UserRole` does) and return any results. Otherwise, create the project mentor
  - DELETEs should remove a mentor from the project

Note that this does not handle the suggestion of projects by attendees. Please comment with any questions or suggestions.

**Comment by tommypacker** [comment]
#44

**Comment by nmagerko** [comment]
Finished by #44
