### ISSUE TITLE
Production Logging Facilities

### ISSUE THREAD

**Issue by nmagerko** [HackIllinois/api-2017#40]
We need a way to log meaningfully in a production environment. Right now, we have a `logging.js` that simply exports the default CLI logger from the `winston` NPM package. Instead, we should export the appropriate logger for the environment.

Ultimately, we need someone to do a bit more research into how this should work, and then implement their findings. We will probably need to write our logs to a dedicated storage space as they will fill up quickly, and we will also want to add a bit more verbosity (tagging which lines of the log output belong to which request will be necessary, along with the route of the request itself).

Please comment below if you're interested in taking this issue.

**Comment by aashishkapur** [comment]
I'll take this

**Comment by nmagerko** [comment]
I'm gonna take back over this

**Comment by nmagerko** [comment]
Finished by #51
