### ISSUE TITLE
Password Reset Form

### ISSUE THREAD

**Issue by AnkitPatanaik** [HackIllinois/api-2017#81]
Password Reset Form has incorrect text which is very confusing.  It's also hard to tell if the request has gone through - some sort of confirmation message would be great.

![image](https://cloud.githubusercontent.com/assets/8581373/22960157/b2d1c3f0-f309-11e6-9915-19b07af75ae2.png)

**Comment by YashoSharma** [comment]
Closing this, this repository is for the back-end api, not the front-end site. I'll open an issue for you on the correct repository.
